#datanodes represent real mysql instance
datanodes:
    -   name: node1
        addr: 10.20.135.213:3306
        user: qing
        password: admin
        db: mixer
        mode: master
    -   name: node2
        addr: 10.20.135.213:3306
        user: qing
        password: admin
        db: mixer
        mode: slave

#schemas supply an unity entrance for client use
#rw_split rule: 
#   write like update, insert will be send to master
#   select will be send to slave
#   if no other rule set and multi nodes have, write/read will random select a node
schemas:
    -   name: mixer
        nodes: 
            - node1
            - node2
        rw_split: true


