#datanodes represent real mysql instance
datanodes:
    -   name: node1:
        addr: 127.0.0.1:3306
        user: root
        password: admin
        mode: master
    -   name: node2:
        addr: 127.0.0.1:3307
        user: root
        password: admin
        mode: slave
#schemas supply an unity entrance for client use
#rw_split rule: 
#   write like update, insert will be send to master
#   select will be send to slave
#   if no other rule set and multi nodes have, write/read will random select a node
schemas:
    -   name: mixer:
        nodes: 
            - node1
            - node2
        rw_split: true


